version: 0.7.{build}
image: Visual Studio 2017
clone_folder: c:\projects\ami

configuration: Release

#clone_depth: 3

platform:
- x86
- x64

environment:
 matrix:
    # Python 2.7
    - PYTHON_VERSION:   "2.7"
      PYTHON32_PATH:    "C:\\Python27"
      PYTHON32_INCLUDE: "C:\\Python27\\include"
      PYTHON32_BINARY:  "C:\\Python27\\python.exe"
      PYTHON32_LIBRARY: "C:\\Python27\\libs\\python27.lib"
      PYTHON64_PATH:    "C:\\Python27-x64"
      PYTHON64_INCLUDE: "C:\\Python27-x64\\include"
      PYTHON64_BINARY:  "C:\\Python27-x64\\python.exe"
      PYTHON64_LIBRARY: "C:\\Python27-x64\\libs\\python27.lib"


    # Python 3.5
    - PYTHON_VERSION:   "3.5"
      PYTHON32_PATH:    "C:\\Python35"
      PYTHON32_INCLUDE: "C:\\Python35\\include"
      PYTHON32_BINARY:  "C:\\Python35\\python.exe"
      PYTHON32_LIBRARY: "C:\\Python35\\libs\\python35.lib"
      PYTHON64_PATH:    "C:\\Python35-x64"
      PYTHON64_INCLUDE: "C:\\Python35-x64\\include"
      PYTHON64_BINARY:  "C:\\Python35-x64\\python.exe"
      PYTHON64_LIBRARY: "C:\\Python35-x64\\libs\\python35.lib"


    # Python 3.6
    - PYTHON_VERSION:   "3.6"
      PYTHON32_PATH:    "C:\\Python36"
      PYTHON32_INCLUDE: "C:\\Python36\\include"
      PYTHON32_BINARY:  "C:\\Python36\\python.exe"
      PYTHON32_LIBRARY: "C:\\Python36\\libs\\python36.lib"
      PYTHON64_PATH:    "C:\\Python36-x64"
      PYTHON64_INCLUDE: "C:\\Python36-x64\\include"
      PYTHON64_BINARY:  "C:\\Python36-x64\\python.exe"
      PYTHON64_LIBRARY: "C:\\Python36-x64\\libs\\python36.lib"



install:
  - ps: if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }

  - ps: if ($env:PLATFORM -eq "x64") { $env:PYTHON_PATH    = $env:PYTHON64_PATH }
  - ps: if ($env:PLATFORM -eq "x64") { $env:PYTHON_INCLUDE = $env:PYTHON64_INCLUDE }
  - ps: if ($env:PLATFORM -eq "x64") { $env:PYTHON_BINARY  = $env:PYTHON64_BINARY }
  - ps: if ($env:PLATFORM -eq "x64") { $env:PYTHON_LIBRARY = $env:PYTHON64_LIBRARY }

  - ps: if ($env:PLATFORM -eq "x86") { $env:PYTHON_PATH    = $env:PYTHON32_PATH }
  - ps: if ($env:PLATFORM -eq "x86") { $env:PYTHON_INCLUDE = $env:PYTHON32_INCLUDE }
  - ps: if ($env:PLATFORM -eq "x86") { $env:PYTHON_BINARY  = $env:PYTHON32_BINARY }
  - ps: if ($env:PLATFORM -eq "x86") { $env:PYTHON_LIBRARY = $env:PYTHON32_LIBRARY }
  - set PATH=%PYTHON_PATH%;%PATH%

  # Upgrade pip
  - python.exe -m pip install --disable-pip-version-check --upgrade pip
  - python.exe -m pip install wheel
  - python.exe -m pip install --upgrade setuptools


build_script:
  - python.exe ./setup.py install
  - python.exe ./setup.py bdist_wheel
  - python.exe -c "import pyAMI;print(pyAMI)"




